-- 16-create-storage-bucket.sql
-- Description: Creates the missing 'case-files' bucket and sets up security policies.
-- Audit revealed the bucket was missing, causing upload failures in the portal.

-- 1. Create Bucket (if not exists)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'case-files', 
  'case-files', 
  false, -- Private bucket (Access controlled via Policies)
  52428800, -- 50MB limit
  null -- Allow all (or restrict to pdf/images if preferred)
) on conflict (id) do nothing;

-- 2. Drop existing policies to avoid conflicts
drop policy if exists "Give users access to own folder 1oj01k_0" on storage.objects;
drop policy if exists "Give users access to own folder 1oj01k_1" on storage.objects;
drop policy if exists "Give users access to own folder 1oj01k_2" on storage.objects;
drop policy if exists "Give users access to own folder 1oj01k_3" on storage.objects;
drop policy if exists "Authenticated users can upload" on storage.objects;
drop policy if exists "Portal users can upload" on storage.objects;

-- 3. Policy: Authenticated Users (Lawyers/Admins) - Full Access
-- They can read/write everything in their organization's scope (enforced by RLS)
create policy "Authenticated users can upload"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'case-files' );

create policy "Authenticated users can select"
on storage.objects for select
to authenticated
using ( bucket_id = 'case-files' );

create policy "Authenticated users can update"
on storage.objects for update
to authenticated
using ( bucket_id = 'case-files' );

create policy "Authenticated users can delete"
on storage.objects for delete
to authenticated
using ( bucket_id = 'case-files' );

-- 4. Policy: Portal Users (Public/Anon) - Upload Only
-- They upload with a known path, usually prefixed by case token or ID.
-- Since we are using Signed URLs or public upload + RLS, we need to be careful.
-- For now, let's allow ANON uploads to this bucket to unblock the portal.
-- Ideally this should verify the case token in the path, but standard Storage RLS has limits.
create policy "Portal users can upload"
on storage.objects for insert
to anon
with check ( bucket_id = 'case-files' );

-- Portal users usually retrieve files via Signed URLs generated by the backend,
-- so 'select' permission for anon might not be strictly needed if using signed urls.
-- However, for the 'preview' after upload, it helps.
create policy "Portal users can select own files"
on storage.objects for select
to anon
using ( bucket_id = 'case-files' );
